#!/bin/sh
RED_LED="24"
GREEN_LED="23"
GPIO="/sys/class/gpio"

start() {
	/root/tally_pokemon.sh start &
}

stop() {
	true
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
